task(issue-111): added button link in job page for viewing backlog
mlee97/SOEN-390-Team5 pull request #114
Opened 2021-03-07 15:06 UTC by abirshah

2021-03-07 17:08 UTC, CeliaCaii requested changes
The backlog button placement is very random in the Job page. View picture for a suggested placement of where the backlog button could be placed:
![image](https://user-images.githubusercontent.com/47066791/110248173-c5036a00-7f3d-11eb-8c60-cfb6716c1f89.png)

2021-03-07 17:11 UTC, CeliaCaii reviewed
The backlog button redirects me to this new page, but I believe we said it should be a pop up modal (similar to the add a bicycle button in Inventory page). However, I think that opening up a new page is also fine, but everyone should agree with it.

![image](https://user-images.githubusercontent.com/47066791/110248248-23c8e380-7f3e-11eb-9138-09964afa5c4d.png)

2021-03-07 19:52 UTC, pirasunt requested changes

2021-03-07 19:52 UTC, pirasunt commented on ERP/resources/views/job-backlog-page.blade.php
> +<div class="container-fluid">
@abirshah Do you think you can add this part to a MODAL in the jobs page?

2021-03-09 00:49 UTC, pirasunt commented on ERP/resources/views/job-backlog-page.blade.php
> +<div class="container-fluid">
@abirshah Looks great now man! Thanks
- However, i think you forgot to remove the old backlog button
![image](https://user-images.githubusercontent.com/31664874/110401310-54e10b00-8047-11eb-9e53-e5fb853abe8f.png)

2021-03-09 00:49 UTC, pirasunt commented
@abirshah I think you forgot to remove the old backlog button.
![image](https://user-images.githubusercontent.com/31664874/110401354-6a563500-8047-11eb-8151-948b826094c2.png)

2021-03-09 01:21 UTC, pirasunt approved these changes
Awesome job!!

2021-03-09 14:30 UTC, CeliaCaii approved these changes

2021-03-10 02:30 UTC, merged