task(issue-112): parts table added to the backlog table
mlee97/SOEN-390-Team5 pull request #116
Opened 2021-03-10 21:37 UTC by abirshah

2021-03-10 23:27 UTC, pirasunt approved these changes
Looks good!

2021-03-10 23:50 UTC, pirasunt requested changes
Hi Shah,

The TA said the backlog would only contain the materials. Can you remove the parts table from the backlog table?
![image](https://user-images.githubusercontent.com/31664874/110714489-75d56780-81d1-11eb-9744-53c6cf49615e.png)

2021-03-11 00:01 UTC, pirasunt approved these changes
I removed the parts table. 
Approved!

2021-03-11 01:28 UTC, CeliaCaii approved these changes

2021-03-11 01:51 UTC, merged