task(issue-179): sales backend populated in the tables with add sales button
mlee97/SOEN-390-Team5 pull request #181
Opened 2021-04-03 17:13 UTC by abirshah

2021-04-03 19:30 UTC, CeliaCaii requested changes

2021-04-03 19:30 UTC, CeliaCaii commented on ERP/routes/web.php
> +
Use the SalesController

2021-04-03 19:30 UTC, CeliaCaii commented on ERP/app/Http/Controllers/AccountantController.php
> -use Illuminate\Http\Request;
Why are you removing this?

2021-04-03 19:30 UTC, CeliaCaii commented on ERP/app/Http/Controllers/AccountantController.php
> +    }
I think this should be in SalesController

2021-04-05 21:10 UTC, pirasunt approved these changes
nice job

2021-04-05 21:49 UTC, CeliaCaii approved these changes

2021-04-05 22:10 UTC, merged