task(issue-84): added comments for inventory controllers
mlee97/SOEN-390-Team5 pull request #86
Opened 2021-03-02 05:36 UTC by mlee97

Added descriptive comments for the controllers used in the inventory page.

2021-03-02 16:47 UTC, CeliaCaii commented on ERP/app/Http/Controllers/BikeController.php
>          $validator = Validator::make($request->all(), [
You have an extra "the" after "Validate that..."

2021-03-02 16:48 UTC, CeliaCaii commented on ERP/app/Http/Controllers/BikeController.php
>          $validator = Validator::make($request->all(), [
You have an extra "the" after "Validate that..."

2021-03-02 17:07 UTC, CeliaCaii commented on ERP/app/Http/Controllers/MaterialController.php
>          $validator = Validator::make($request->all(), [
You have an extra "the" after "Validate that..."

2021-03-02 17:07 UTC, CeliaCaii commented on ERP/app/Http/Controllers/MaterialController.php
> +        //Validate that the all the following fields are specified and that they match their respective data type.
You have an extra "the" after "Validate that..."

2021-03-02 17:08 UTC, CeliaCaii commented on ERP/app/Http/Controllers/MaterialController.php
> +        //Validate that the all the following fields are specified and that they match their respective data type.
You have an extra "the" after "Validate that..."

2021-03-02 17:08 UTC, CeliaCaii commented on ERP/app/Http/Controllers/PartController.php
> +        //Validate that the all the following fields are specified and that they match their respective data type.
You have an extra "the" after "Validate that..."

2021-03-02 17:09 UTC, CeliaCaii commented on ERP/app/Http/Controllers/PartController.php
> +        //Validate that the all the following fields are specified and that they match their respective data type.
You have an extra "the" after "Validate that..."

2021-03-02 17:15 UTC, CeliaCaii requested changes
There are recurring typos to be fixed. Otherwise, good work!!!

2021-03-02 17:44 UTC, CeliaCaii approved these changes

2021-03-03 16:39 UTC, pirasunt approved these changes

2021-03-03 16:40 UTC, merged